import http from 'node:http';
const host = process.env.HOST || '127.0.0.1';
const port = Number(process.env.FRONTEND_PORT);
const apiPort = Number(process.env.BACKEND_PORT);
const page = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>LegalForms Governed Runtime</title><style>body{font:16px system-ui;background:#eef2f7;color:#172033;margin:0}main{max-width:760px;margin:10vh auto;background:white;padding:3rem;border-radius:18px;box-shadow:0 18px 60px #1222}h1{color:#173b67}.tag{display:inline-block;background:#dcecff;padding:.4rem .8rem;border-radius:999px}form{display:grid;gap:.8rem;margin-top:1.5rem}label,input,button{font:inherit}input,button{padding:.75rem}button{cursor:pointer}.status{min-height:1.5rem}</style></head><body><main><span class="tag">Governed runtime</span><h1>LegalForms</h1><p>Authenticated legal-document readiness and provider evidence are available through the protected API.</p><form id="login"><label>Email<input id="email" type="email" autocomplete="username" required></label><label>Password<input id="password" type="password" autocomplete="current-password" required></label><button id="demo" type="button">Auto Fill Demo Credentials</button><button type="submit">Sign In</button></form><section id="dashboard" hidden><h2>Authenticated LegalForms Dashboard</h2><p id="identity"></p><p>Governed document readiness and provider evidence are available.</p></section><p id="status" class="status" role="status"></p></main><script>'use strict';let token='';const login=document.getElementById('login');const dashboard=document.getElementById('dashboard');const status=document.getElementById('status');document.getElementById('demo').addEventListener('click',async()=>{status.textContent='Loading demo credentials…';const response=await fetch('/api/auth/demo-credentials',{cache:'no-store'});const body=await response.json();if(!response.ok){status.textContent='Demo credentials unavailable.';return}email.value=body.email;password.value=body.password;status.textContent='Demo credentials loaded. Select Sign In.'});login.addEventListener('submit',async event=>{event.preventDefault();const response=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});const body=await response.json();password.value='';if(!response.ok){status.textContent='Sign in failed.';return}token=body.token;const me=await fetch('/api/auth/me',{headers:{authorization:'Bearer '+token}});const actor=await me.json();login.hidden=true;dashboard.hidden=false;document.getElementById('identity').textContent='Signed in as '+actor.email;status.textContent='Authenticated session active.'});</script></body></html>`;
const server = http.createServer((req, res) => {
  if (req.url?.startsWith('/api/') || req.url === '/healthz' || req.url === '/readyz') {
    const proxy = http.request({ hostname: host, port: apiPort, path: req.url, method: req.method, headers: req.headers }, (upstream) => { res.writeHead(upstream.statusCode || 502, upstream.headers); upstream.pipe(res); });
    proxy.on('error', () => { res.writeHead(502); res.end('API unavailable'); }); req.pipe(proxy); return;
  }
  res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); res.end(page);
});
server.listen(port, host, () => console.log(`LegalForms UI listening on http://${host}:${port}`));
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => server.close(() => process.exit(0)));
